export enum fontFamily{
    regular='SF-Pro-Text-Regular',
    regularItalic='SF-Pro-Text-RegularItalic',
    medium='SF-Pro-Text-Medium',
    mediumItalic='SF-Pro-Text-MediumItalic',
    semiBold='SF-Pro-Text-Semibold',
    semiBoldItalic='SF-Pro-Text-SemiboldItalic',
    light='SF-Pro-Text-Light',
    lightItalic='SF-Pro-Text-LightItalic',
    bold='SF-Pro-Text-Bold',
    boldItalic='SF-Pro-Text-BoldItalic',
    heavy='SF-Pro-Text-Heavy',
    heavyItalic='SF-Pro-Text-HeavyItalic',
    robotoBlack='Roboto-Black',
    robotoBlackItalic='Roboto-BlackItalic',
    robotoBold='Roboto-Bold',
    robotoBoldItalic='Roboto-BoldItalic',
    robotoItalic='Roboto-Italic',
    robotoLight='Roboto-Light',
    robotoLightItalic='Roboto-LightItalic',
    robotoMedium='Roboto-Medium',
    robotoRegular='Roboto-Regular',
    robotoThin='Roboto-Thin',
    robotoThinItalic='Roboto-ThinItalic',
    
}