enum ImagePaths {
    signupLayout = require('../../assets/images/signupLayout.png'),
    logo = require('../../assets/images/logo.png'),
    smartphone=require('../../assets/images/smartphone.png'),
    facebook = require('../../assets/images/facebook.png'),
    google = require('../../assets/images/google.png'),
    apple=require('../../assets/images/apple.png'),
    email=require('../../assets/images/email.png'),
    bottomLayout=require('../../assets/images/bottomLayout.png'),
    close=require('../../assets/images/close.png'),
    hsLayout=require('../../assets/images/HSLayout.png'),
    hsBottomLayout=require('../../assets/images/HSBottomLayout.png'),
    downArrow=require('../../assets/images/downArrow.png'),
    registerFormTopLayout=require('../../assets/images/registerFormTopLayout.png'),
    edit=require('../../assets/images/edit.png'),
    loaderBg=require('../../assets/images/loaderBg.png'),
    loaderLogo=require('../../assets/images/loaderLogo.png'),
    loaderIcon=require('../../assets/images/loaderIcon.png'),
    home=require('../../assets/images/home.png'),
    more=require('../../assets/images/more.png'),
    compatibility=require('../../assets/images/compatibility.png'),
    remedies=require('../../assets/images/remedies.png'),
    bottomTabBg=require('../../assets/images/bottomTabBg.png'),
    bell=require('../../assets/images/bell.png'),
    aries=require('../../assets/images/aries.png'),
    calendar=require('../../assets/images/calendar.png'),
    sun=require('../../assets/images/sun.png'),
    share=require('../../assets/images/share.png'),
    settings=require('../../assets/images/settings.png'),
    arrow=require('../../assets/images/arrow.png'),
    cross=require('../../assets/images/cross.png'),
  } 
export { ImagePaths };
  
