const enum  screenName {
    WELCOME = "WELCOME",
    TERMS_AND_CONDITION='TERMS_AND_CONDITION',
    PRIVACY_POLICY='PRIVACY_POLICY',
    MOBILE_NUMBER_SIGNUP='MOBILE_NUMBER_SIGNUP',
  }
export default screenName