export type RootStackParamList = {
    setOptions: any;
    addListener: any;
    navigation: any;
    navigate: any;
    goBack: any;
    WELCOME: undefined;
    TERMS_AND_CONDITION:undefined;
    PRIVACY_POLICY:undefined;
    SIGN_UP_WITH_PHONE:undefined;
    SIGN_UP_WITH_EMAIL:undefined;
    REGISTER_FORM:undefined;
    OTP_VERIFICATION:undefined;
    LOADER_SCREEN:undefined;
    DASHBOARD:undefined;
    NOTIFICATION:undefined;
    SETTINGS:undefined;
    SELECT_DATE_SCREEN:undefined;
    SELECT_TIME_SCREEN:undefined;
    FOCUS_OF_THE_DAY:undefined;
    CALENDAR_ADVICE:undefined;
    MANAGE_INTEREST:undefined;
  };
